# Generated by Django 2.2.2 on 2019-06-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='action',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
