# Generated by Django 2.2.2 on 2019-06-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='action',
            field=models.CharField(default=200, max_length=255),
        ),
    ]
